"use strict";
exports.__esModule = true;
exports.PATH_TO_COOKBOOK_EXAMPLES = exports.DYNAMIC_TERMS_REGEXS = exports.DYNAMIC_PREDICATE_REGEXS = exports.PATH_TO_JSON_DICTIONARY = void 0;
var ROOT_DIR = "assets/";
var DLV_CODE_DIR = "code/dlv/";
var FULL_PATH = ROOT_DIR + DLV_CODE_DIR;
var COOKBOOK_EXTENSION_FILE = ".txt";
exports.PATH_TO_JSON_DICTIONARY = {
    CONSTANTS: ROOT_DIR + "constants.json",
    AGGREGATES: ROOT_DIR + "aggregates.json",
    BUILTINS: ROOT_DIR + "builtins.json"
};
exports.DYNAMIC_PREDICATE_REGEXS = {
    FULL_REGEX: /(\w+\s*\(\s*\w+(?:\s*,\s*\w+\s*)*\s*\))\s*(?::-|\||\.|,)/g,
    AUX_REGEX: /(\w+)\s*\(/g
};
exports.DYNAMIC_TERMS_REGEXS = {
    FULL_REGEX: /\w+\s*\(\s*\w+(?:\s*,\s*\w+\s*)*\s*\)\s*(?::-|\||\.|,)/g
};
exports.PATH_TO_COOKBOOK_EXAMPLES = {
    ADVANCED_KNAPSACK_PROBLEM: FULL_PATH + "ADVANCED_KNAPSACK_PROBLEM" + COOKBOOK_EXTENSION_FILE,
    KNAPSACK_PROBLEM: FULL_PATH + "KNAPSACK_PROBLEM" + COOKBOOK_EXTENSION_FILE,
    THREE_COLORABILITY: FULL_PATH + "3_COLORABILITY" + COOKBOOK_EXTENSION_FILE,
    HAMILTON_PATH: FULL_PATH + "HAMILTON_PATH" + COOKBOOK_EXTENSION_FILE,
    MINIMUM_SPANNING_TREE: FULL_PATH + "MINIMUM_SPANNING_TREE" + COOKBOOK_EXTENSION_FILE,
    SEATING: FULL_PATH + "SEATING" + COOKBOOK_EXTENSION_FILE,
    STRATEGIC_COMPANIES: FULL_PATH + "STRATEGIC_COMPANIES" + COOKBOOK_EXTENSION_FILE,
    VERTEX_COVER: FULL_PATH + "VERTEX_COVER" + COOKBOOK_EXTENSION_FILE
};
